#!/usr/bin/env python3
"""Minimal PDF generation helper using reportlab.

Usage:
    python3 generate_pdf.py --output output.pdf --title "Document Title"

This script creates a basic PDF with a title page. For complex documents,
write a custom Python script using reportlab directly.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, help="Output PDF file path")
    parser.add_argument("--title", default="Untitled Document", help="Document title")
    parser.add_argument(
        "--body",
        default="This document was generated by the pdf skill.",
        help="Body text (first paragraph)",
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    story = []

    title_style = styles["Title"]
    body_style = styles["Normal"]

    story.append(Paragraph(args.title, title_style))
    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(args.body, body_style))

    doc.build(story)
    print(output_path)


if __name__ == "__main__":
    main()